server:
  port: 80
spring:
  main:
    allow-circular-references: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    password: root123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            required: true
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

    username: xolbekovdoniyor2001@gmail.com
    password: dacfobtyimmulsmi


#      shaxsiy variable lar
jwt:
  access:
    secret: buMeningParolim
  refresh:
    secret: buRefreshniParoli