package ai.ecma.appwarehouseproject.enums;

public enum PermissionEnums {

    DOWNLOAD_ATTACHMENT,
    UPLOAD_ATTACHMENT,

    VIEW_CATEGORY,
    VIEW_CATEGORIES,
    ADD_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,

    VIEW_CURRENCY,
    VIEW_CURRENCIES,
    ADD_CURRENCY,
    UPDATE_CURRENCY,
    DELETE_CURRENCY,

    VIEW_INPUT_PRODUCT,
    VIEWS_INPUT_PRODUCTS,
    ADD_INPUT_PRODUCT,
    UPDATE_INPUT_PRODUCT,

    VIEW_INCOME,
    VIEW_INCOMES,
    ADD_INCOME,
    UPDATE_INCOME,

    VIEW_MEASURE,
    VIEW_MEASURES,
    ADD_MEASURE,
    UPDATE_MEASURE,
    DELETE_MEASURE,

    VIEW_OUTPUT_PRODUCT,
    VIEWS_OUTPUT_PRODUCTS,
    ADD_OUTPUT_PRODUCT,
    UPDATE_OUTPUT_PRODUCT,

    VIEW_OUTCOME,
    VIEW_OUTCOMES,
    ADD_OUTCOME,
    UPDATE_OUTCOME,

    VIEW_PRODUCT,
    VIEW_PRODUCTS,
    ADD_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,

    VIEW_ROLE,
    VIEW_ROLES,
    ADD_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    MANAGE_ROLE_TO_USER,
    DELETE_PERMISSIONS_ROLE,

    VIEW_SUPPLIER,
    VIEW_SUPPLIERS,
    ADD_SUPPLIER,
    UPDATE_SUPPLIER,
    DELETE_SUPPLIER,

    VIEW_WAREHOUSE,
    VIEW_WAREHOUSES,
    ADD_WAREHOUSE,
    UPDATE_WAREHOUSE,
    DELETE_WAREHOUSE;

}
